on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "current/**"

jobs:
  update_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pymupdf
      - name: Run Python script
        run: |
          rm preview/*
          python scripts/update_preview.py
      - name: Commit changes
        run: |
          git config --global user.name "Larry H."
          git config --global user.email "111525408+larryh12@users.noreply.github.com"
          git add -A
          git commit --allow-empty -m "Updated on $(date)"
          git push --force
